[package]
name = "wgsl_to_wgpu_macro"
version = "0.10.1"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
syn = "2.0"
quote = "1.0"
proc-macro2 = "1.0"
wgsl_to_wgpu = { git = "https://github.com/cbbowen/wgsl_to_wgpu.git" }
regex = "1.10"
# naga = { version="22.1", features = ["wgsl-in"] }
naga = { git = "https://github.com/cbbowen/wgpu.git", features = ["wgsl-in"] }

[features]
track_path = []
