[package]
name = "wgsl_to_wgpu_macro"
version = "0.10.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
syn = "2.0"
quote = "1.0"
proc-macro2 = "1.0"
wgsl_to_wgpu = { git = "https://github.com/ScanMountGoat/wgsl_to_wgpu.git" }
